### ISSUE TITLE
dav1d hangs when using threads

### ISSUE THREAD

**Issue by linkmauve** [ptitSeb/box86#253]
I wanted to evaluate the performance hit of box86 on my Nintendo Switch in some pure CPU benchmark with heavy SIMD usage, [dav1d](https://www.videolan.org/projects/dav1d.html) is a perfect case for that.

On [a particular benchmark from Netflix](http://download.opencontent.netflix.com/?prefix=AV1/Chimera/Old/) (8-bit, 1080p) I got 0.39 fps when running with `--framethread 1 --tilethread 1` under box86, while the native ARM binary gave me 13.51 fps in the same conditions.

Using `--framethread 4 --tilethread 4` natively gives 38.44 fps instead, which goes from unplayable to playable at this resolution, but makes the i686 version under box86 hang forever before decoding even the first frame.

**Comment by ptitSeb** [comment]
A CPU benchmark, interesting. Is there some pre-built binary somewhere or thay have to be built from sources?

**Comment by linkmauve** [comment]
You could download the Debian package for it (requires https://packages.debian.org/sid/i386/libdav1d4/download and https://packages.debian.org/sid/i386/dav1d/download), it’s dynamically linked but only requires its own library besides what box86 already provides.

**Comment by ptitSeb** [comment]
Ah ok, I'll grab debian version. I'll see why it's so slow and why it freeze on multi-thread.

**Comment by ptitSeb** [comment]
I have added a few opcode to the dynarec that should improve performances. But I haven't looked at the freeze yet (probably not before tomorrow anyway).

**Comment by linkmauve** [comment]
That already gave me almost a 10× speedup, from 0.39 fps to 3.13 fps, thanks for that!

**Comment by ptitSeb** [comment]
I don't reproduce the hang on my Pi4 when using multi thread.
I used this command line: ` ./dav1d --framethreads 4 --tilethreads 4 -i Chimera-AV1-8bit-480x270-552kbps.ivf -o test.md5` for a quick test. Should I use something different?

**Comment by ptitSeb** [comment]
That gives me this output:
``` 
$ ./dav1d --framethreads 4 --tilethreads 4 -i Chimera-AV1-8bit-480x270-552kbps.ivf -o test.md5
Box86 with Dynarec v0.1.5 b61bb908 built on Nov 21 2020 11:48:38
dav1d 0.7.1 - by VideoLAN
Decoded 8929/8929 frames (100.0%) - 70.59/1784.02 fps (0.04x)
```

**Comment by linkmauve** [comment]
Here it works in gdb (wouldn’t be fun otherwise…), but stops after printing “dav1d 0.7.1 - by VideoLAN” when it’s not being debugged.

**Comment by ptitSeb** [comment]
I must have messed up one of the dynarec opcode.
I'll need to debug that

The see why it lookup on your side, you can try to use `gdb -pid XXXX` on another terminal to attache to the process and see where it's stuck.

**Comment by linkmauve** [comment]
It’s always stuck here in all but one threads:
```gdb
(gdb) bt
#0  0xe8bb4764 in pthread_cond_wait@@GLIBC_2.4 () from /usr/lib/libpthread.so.0
#1  0x6291cb90 in iFEpp (emu=0x64146900, fcn=1653691956) at ../src/wrapped/generated/wrapper.c:2209
#2  0xe78e991c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

And one tile thread which is stuck at:
```gdb
(gdb) bt
#0  0xe8bb2f70 in pthread_rwlock_wrlock () from /usr/lib/libpthread.so.0
#1  0x629cfcb0 in AddNewDynablock (dynablocks=<optimized out>, addr=addr@entry=3889348829, with_marks=1654455472, created=0xe6cfdad8, created@entry=0xe6cfdad0) at ../src/dynarec/dynablock.c:550
#2  0x629d011c in internalDBGetBlock (emu=emu@entry=0x641abf20, addr=addr@entry=3889348829, filladdr=filladdr@entry=3889348829, create=create@entry=1, current=0xe6e69fe8) at ../src/dynarec/dynablock.c:623
#3  0x629d02a4 in DBGetBlock (emu=emu@entry=0x641abf20, addr=3889348829, create=create@entry=1, current=current@entry=0xe6cfdb98) at ../src/dynarec/dynablock.c:642
#4  0x6291849c in DynaCall (emu=emu@entry=0x641abf20, addr=1657788320) at ../src/dynarec/dynarec.c:127
#5  0x62874bcc in RunFunctionWithEmu (emu=0x641abf20, QuitOnLongJump=QuitOnLongJump@entry=0, fnc=<optimized out>, nargs=1) at ../src/tools/callback.c:353
#6  0x62911ff8 in pthread_routine (p=0x6419a188) at ../src/libtools/threads.c:219
#7  0xe8bacf60 in start_thread () from /usr/lib/libpthread.so.0
#8  0xe8b02cd8 in ?? () from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by ptitSeb** [comment]
Just to note: I have made some update this morning, and start_pthread doesn't use RunFunctionWithEmu anymore. I don't think that will fix the lock issue.
I don't why it would be blocked at this place tho, but I'll first fix the "bad md5" issue anyway.

**Comment by ptitSeb** [comment]
Ok, with that last commit, I think I have fixed the freeze problem.

All previous commit should have fixed the md5 issue pb.

So, all seems fixed now, you can test again.

**Comment by linkmauve** [comment]
I still get a different md5 than on native, but a different one from before: a42e840a81521ae469e969d01609c007

**Comment by ptitSeb** [comment]
Ah, ok. I did some test it seemed ok. I guess I haven't tested enough.

**Comment by ptitSeb** [comment]
The ticket got closed automaticaly because of the commit title. I have reopen it to let you test and close it yourself if it's ok on your side.

**Comment by linkmauve** [comment]
It works perfectly now, thanks! \o/
