### ISSUE TITLE
Crypt of the Necrodancer: weak symbol / symbols not found

### ISSUE THREAD

**Issue by ITotalJustice** [ptitSeb/box86#35]
```
pi@raspberrypi:/media/pi/Seagate Expansion Drive/linux-games/crypt-of-the-necrodancer/data/noarch/game $ BOX86_LD_LIBRARY_PATH=.:fmod/lib/:/lib:./lib:.:./lib/i686-pc-linux-gnu:./lib32:/usr/i686-linux-gnu/lib box86 NecroDancerBOX86_LD_LIBRARY_PATH: ./:fmod/lib/:/lib/:./lib/:./:./lib/i686-pc-linux-gnu/:./lib32/:/usr/i686-linux-gnu/lib/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for NecroDancer
Using native(wrapped) libGL.so.1
Using emulated ./fmod/lib/libfmodex.so
Using native(wrapped) libdl.so.2
Using emulated /usr/i686-linux-gnu/lib/libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/i686-linux-gnu/lib/libgcc_s.so.1
Using emulated libglfw.so.2
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libopenal.so.1
Using native(wrapped) libogg.so.0
Using native(wrapped) libvorbis.so.0
Error: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT @0xb669d198 (0x6b676)
Error: Weak Symbol _ZGTtdlPv not found, cannot apply R_386_JMP_SLOT @0xb669d474 (0x6c1e6)
Error: Symbol FMOD_Resampler_Linear_PCM16_Stereo not found, cannot apply R_386_JMP_SLOT @0xb6824040 (0xfa56)
Error: Symbol FMOD_DSP_Connection_Mix7_1To7_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xb682412c (0xfe06)
Error: Symbol FMOD_Resampler_Linear_PCM16_Mono not found, cannot apply R_386_JMP_SLOT @0xb6824330 (0x10616)
Error: Symbol FMOD_DSP_Connection_MixStereoToStereo_SIMD not found, cannot apply R_386_JMP_SLOT @0xb682439c (0x107c6)
Error: Symbol FMOD_DSP_Convert_FloatToPCM16 not found, cannot apply R_386_JMP_SLOT @0xb68243c4 (0x10866)
Error: Symbol FMOD_DSP_Connection_MixMonoToStereo_SIMD not found, cannot apply R_386_JMP_SLOT @0xb68243f0 (0x10916)
Error: Symbol FMOD_DSP_Connection_MixMonoTo5_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xb6824434 (0x10a26)
Error: Symbol FMOD_DSP_Connection_Mix5_1To5_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xb6824510 (0x10d96)
Error: Symbol FMOD_DSP_Distortion_SIMD not found, cannot apply R_386_JMP_SLOT @0xb68245c0 (0x11056)
Error: Symbol FMOD_OS_SupportsSSE not found, cannot apply R_386_JMP_SLOT @0xb6824700 (0x11556)
Error: Symbol FMOD_DSP_Connection_MixMonoTo7_1_SIMD not found, cannot apply R_386_JMP_SLOT @0xb6824744 (0x11666)
Error: Symbol XConvertCase not found, cannot apply R_386_JMP_SLOT @0xb6f5e0a8 (0x36c6)
Segmentation fault
```

**Comment by ptitSeb** [comment]
I added `XConvertCase` but I don't understand, like with Prison Architect, why the fmod symbols are not found.
can you run `readelf -aW ./fmod/lib/libfmodex.so | grep FMOD_DSP_Connection_Mix7_1To7_1_SIMD` and paste the result here?

**Comment by ITotalJustice** [comment]
here you go
```
readelf -aW ./fmod/lib/libfmodex.so | grep FMOD_DSP_Connection_Mix7_1To7_1_SIMD
0014212c  00021807 R_386_JUMP_SLOT        000d335e   FMOD_DSP_Connection_Mix7_1To7_1_SIMD
   536: 000d335e     0 NOTYPE  GLOBAL DEFAULT   11 FMOD_DSP_Connection_Mix7_1To7_1_SIMD
   766: 000d335e     0 NOTYPE  GLOBAL DEFAULT   11 _FMOD_DSP_Connection_Mix7_1To7_1_SIMD
```

**Comment by ptitSeb** [comment]
Ok, looks like a regular symbol. I should have a bug in the elf symbol parser then...

**Comment by ptitSeb** [comment]
So, I just pushed a changed where I referenced also symbol with "NOTYPE" type. That should help Crypt of the Necrodancer. Not sure it's enough to make it start.

**Comment by ITotalJustice** [comment]
Just tried, getting much less errors now. Still not booting yet.
```
BOX86_LD_LIBRARY_PATH=.:fmod/lib/:/lib:./lib:.:./lib/i686-pc-linux-gnu:./lib32:/usr/i686-linux-gnu/lib box86 NecroDancer
BOX86_LD_LIBRARY_PATH: ./:fmod/lib/:/lib/:./lib/:./:./lib/i686-pc-linux-gnu/:./lib32/:/usr/i686-linux-gnu/lib/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for NecroDancer
Using native(wrapped) libGL.so.1
Using emulated ./fmod/lib/libfmodex.so
Using native(wrapped) libdl.so.2
Using emulated /usr/i686-linux-gnu/lib/libstdc++.so.6
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/i686-linux-gnu/lib/libgcc_s.so.1
Using emulated libglfw.so.2
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libX11.so.6
Using native(wrapped) libopenal.so.1
Using native(wrapped) libogg.so.0
Using native(wrapped) libvorbis.so.0
Error: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT @0xb669b198 (0x6b676)
Error: Weak Symbol _ZGTtdlPv not found, cannot apply R_386_JMP_SLOT @0xb669b474 (0x6c1e6)
Segmentation fault
```

**Comment by ITotalJustice** [comment]
Here is the bt full , hopefully its helpful it some way :)
```
Program received signal SIGSEGV, Segmentation fault.
GetNativeFnc (fnc=fnc@entry=0) at /home/pi/box86/src/tools/bridge.c:83
83	    if(b->CC != 0xCC || b->S!='S' || b->C!='C' || (b->C3!=0xC3 && b->C3!=0xC2))
(gdb) bt full
#0  GetNativeFnc (fnc=fnc@entry=0) at /home/pi/box86/src/tools/bridge.c:83
        b = 0x0
#1  0xa805e21c in my_XSetErrorHandler (emu=emu@entry=0xa80cbb20, handler=0x0) at /home/pi/box86/src/wrapped/wrappedlibx11.c:218
        lib = 0xa81862a8
        my = 0xa818b498
        cb = 0x0
        ret = <optimized out>
        old = 0x0
#2  0xa8018200 in pFEp (emu=emu@entry=0xa80cbb20, fcn=fcn@entry=2818957800) at /home/pi/box86/src/wrapped/generated/wrapper.c:1020
        fn = 0xa805e1e8 <my_XSetErrorHandler>
#3  0xa8055058 in x86Int3 (emu=0xa80cbb20) at /home/pi/box86/src/emu/x86int3.c:186
        w = 0xa80181e8 <pFEp>
        addr = 2818957800
#4  0xa8037134 in Run (emu=0xa80cbb20) at /home/pi/box86/src/emu/x86run.c:865
        opcode = <optimized out>
        nextop = <optimized out>
        oped = <optimized out>
        ea1 = <optimized out>
        tmp8u = <optimized out>
        tmp8u2 = <optimized out>
        tmp8s = <optimized out>
        tmp16u = <optimized out>
        tmp16u2 = <optimized out>
        tmp16s = <optimized out>
        tmp32u = <optimized out>
        tmp32u2 = <optimized out>
        tmp32u3 = 0
        tmp32s = <optimized out>
        tmp64u = <optimized out>
        tmp64s = -6332746305229713208
        ip = <optimized out>
        old_ip = 2820509896
        d = -1.5329190383901244e-115
        f = -7.2258585e-15
        ll = <optimized out>
        opex = <optimized out>
        eax1 = {q = {12109213273695238944, 13185031010008195664}, sq = {-6337530800014312672, -5261713063701355952}, d = {-9.062875132321178e-116, -7.4661251305002615e-44}, f = {-7.81213744e-15, -7.8030708e-15, -7.7928793e-15, 
            -7.46965452e-06}, ud = {2819406624, 2819395920, 2819383888, 3069879256}, sd = {-1475560672, -1475571376, -1475583408, -1225088040}, uw = {47904, 43020, 37200, 43020, 25168, 43020, 41944, 46842}, sw = {-17632, -22516, 
            -28336, -22516, 25168, -22516, -23592, -18694}, ub = " \273\f\250P\221\f\250Pb\f\250", <incomplete sequence \372\266>, sb = " \273\f\250P\221\f\250Pb\f\250", <incomplete sequence \372\266>}
        opem = <optimized out>
        baseopcodes = {0xa80371a4 <Run+83244>, 0xa8037264 <Run+83436>, 0xa8037320 <Run+83624>, 0xa8037458 <Run+83936>, 0xa80373e0 <Run+83816>, 0xa803741c <Run+83876>, 0xa8036654 <Run+80348>, 0xa803667c <Run+80388>, 
          0xa8035fdc <Run+78692>, 0xa8036094 <Run+78876>, 0xa8036148 <Run+79056>, 0xa8037c8c <Run+86036>, 0xa8037ac8 <Run+85584>, 0xa8037afc <Run+85636>, 0xa8022fb8 <Run+832>, 0xa80366a4 <Run+80428>, 0xa8037b30 <Run+85688>, 
          0xa8037be0 <Run+85864>, 0xa8037698 <Run+84512>, 0xa8037748 <Run+84688>, 0xa80377f4 <Run+84860>, 0xa8037820 <Run+84904>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa803784c <Run+84948>, 0xa80378c0 <Run+85064>, 
          0xa803796c <Run+85236>, 0xa8037a1c <Run+85412>, 0xa80334e0 <Run+67688>, 0xa8036fdc <Run+82788>, 0xa8035c9c <Run+77860>, 0xa8035cc4 <Run+77900>, 0xa8036e70 <Run+82424>, 0xa8036f28 <Run+82608>, 0xa8036df4 <Run+82300>, 
          0xa8037070 <Run+82936>, 0xa8037008 <Run+82832>, 0xa803703c <Run+82884>, 0xa8022fb8 <Run+832>, 0xa80351e8 <Run+75120>, 0xa8036918 <Run+81056>, 0xa80369d8 <Run+81248>, 0xa8036a94 <Run+81436>, 0xa8036b54 <Run+81628>, 
          0xa8036c10 <Run+81816>, 0xa8036c4c <Run+81876>, 0xa8035214 <Run+75164>, 0xa8023910 <Run+3224>, 0xa8036c88 <Run+81936>, 0xa8036d40 <Run+82120>, 0xa80361c4 <Run+79180>, 0xa803627c <Run+79364>, 0xa8036330 <Run+79544>, 
          0xa8036364 <Run+79596>, 0xa8022fb8 <Run+832>, 0xa802393c <Run+3268>, 0xa8036398 <Run+79648>, 0xa8036408 <Run+79760>, 0xa80364b0 <Run+79928>, 0xa803655c <Run+80100>, 0xa8036604 <Run+80268>, 0xa803662c <Run+80308>, 
          0xa8022fb8 <Run+832>, 0xa80246ec <Run+6772>, 0xa8024718 <Run+6816>, 0xa802471c <Run+6820>, 0xa8024720 <Run+6824>, 0xa8023968 <Run+3312>, 0xa802396c <Run+3316>, 0xa8023970 <Run+3320>, 0xa8022e98 <Run+544>, 
          0xa8022e98 <Run+544>, 0xa8023974 <Run+3324>, 0xa8023978 <Run+3328>, 0xa802397c <Run+3332>, 0xa8023980 <Run+3336>, 0xa8023984 <Run+3340>, 0xa8023988 <Run+3344>, 0xa8022e5c <Run+484>, 0xa8022e5c <Run+484>, 
          0xa80239b8 <Run+3392>, 0xa80239bc <Run+3396>, 0xa80239c0 <Run+3400>, 0xa80239c4 <Run+3404>, 0xa802398c <Run+3348>, 0xa80239c8 <Run+3408>, 0xa8022f04 <Run+652>, 0xa8022f04 <Run+652>, 0xa80239cc <Run+3412>, 
          0xa80239d0 <Run+3416>, 0xa80239d4 <Run+3420>, 0xa80239d8 <Run+3424>, 0xa80239dc <Run+3428>, 0xa80239e0 <Run+3432>, 0xa8022e28 <Run+432>, 0xa8022e28 <Run+432>, 0xa80239e4 <Run+3436>, 0xa802adc8 <Run+33104>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802ae58 <Run+33248>, 0xa802300c <Run+916>, 0xa80261ac <Run+13620>, 0xa80261e4 <Run+13676>, 0xa8026210 <Run+13720>, 0xa80328bc <Run+64580>, 
          0xa80328e8 <Run+64624>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8032994 <Run+64796>, 0xa8032a30 <Run+64952>, 0xa80329c8 <Run+64848>, 0xa80329fc <Run+64900>, 
          0xa8031ef0 <Run+62072>, 0xa80331f4 <Run+66940>, 0xa803317c <Run+66820>, 0xa80331b4 <Run+66876>, 0xa80330ac <Run+66612>, 0xa80330e0 <Run+66664>, 0xa8033114 <Run+66716>, 0xa8033148 <Run+66768>, 0xa8032d34 <Run+65724>, 
          0xa8032d6c <Run+65780>, 0xa8032da4 <Run+65836>, 0xa8032ddc <Run+65892>, 0xa8032e20 <Run+65960>, 0xa8032ed0 <Run+66136>, 0xa8022fb8 <Run+832>, 0xa8032f88 <Run+66320>, 0xa8033000 <Run+66440>, 0xa8031e48 <Run+61904>, 
          0xa803272c <Run+64180>, 0xa8032604 <Run+63884>, 0xa80326c4 <Run+64076>, 0xa8032384 <Run+63244>, 0xa8032424 <Run+63404>, 0xa80324c8 <Run+63568>, 0xa8022fb8 <Run+832>, 0xa8032568 <Run+63728>, 0xa8022fb8 <Run+832>, 
          0xa80322b0 <Run+63032>, 0xa8032354 <Run+63196>, 0xa8032370 <Run+63224>, 0xa8032374 <Run+63228>, 0xa8032378 <Run+63232>, 0xa803237c <Run+63236>, 0xa8032380 <Run+63240>, 0xa8022ed4 <Run+604>, 0xa8022ed4 <Run+604>, 
          0xa8031f24 <Run+62124>, 0xa8031f48 <Run+62160>, 0xa8022fb8 <Run+832>, 0xa8031f70 <Run+62200>, 0xa8031f8c <Run+62228>, 0xa8031fd0 <Run+62296>, 0xa803201c <Run+62372>, 0xa8032078 <Run+62464>, 0xa80320b0 <Run+62520>, 
--Type <RET> for more, q to quit, c to continue without paging--
          0xa80320d4 <Run+62556>, 0xa80320f8 <Run+62592>, 0xa803211c <Run+62628>, 0xa8032140 <Run+62664>, 0xa8032190 <Run+62744>, 0xa80321e0 <Run+62824>, 0xa8032234 <Run+62908>, 0xa8032288 <Run+62992>, 0xa802a194 <Run+29980>, 
          0xa802a1bc <Run+30020>, 0xa802a200 <Run+30088>, 0xa802a244 <Run+30156>, 0xa802a280 <Run+30216>, 0xa802a2bc <Run+30276>, 0xa802a308 <Run+30352>, 0xa802a354 <Run+30428>, 0xa802a358 <Run+30432>, 0xa8022f90 <Run+792>, 
          0xa8022f90 <Run+792>, 0xa802477c <Run+6916>, 0xa8024778 <Run+6912>, 0xa8022f68 <Run+752>, 0xa8022f68 <Run+752>, 0xa8024780 <Run+6920>, 0xa8024784 <Run+6924>, 0xa8024788 <Run+6928>, 0xa80259e0 <Run+11624>, 
          0xa80259e4 <Run+11628>, 0xa80259e8 <Run+11632>, 0xa8022cfc <Run+132>, 0xa8022cfc <Run+132>, 0xa80259ec <Run+11636>, 0xa8025a9c <Run+11812>, 0xa8024724 <Run+6828>, 0xa8024754 <Run+6876>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8025ba0 <Run+12072>, 0xa8025bf8 <Run+12160>...}
        opcodes0f = {0xa8022fb8 <Run+832> <repeats 16 times>, 0xa80366bc <Run+80452>, 0xa8036780 <Run+80648>, 0xa8036844 <Run+80844>, 0xa802ef58 <Run+49888>, 0xa802f03c <Run+50116>, 0xa802f124 <Run+50348>, 0xa802f1f8 <Run+50560>, 
          0xa802f2d8 <Run+50784>, 0xa802f3b8 <Run+51008>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802f450 <Run+51160>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802f494 <Run+51228>, 0xa802f5b8 <Run+51520>, 0xa802f6e0 <Run+51816>, 
          0xa8022fb8 <Run+832>, 0xa8032a64 <Run+65004>, 0xa8032b60 <Run+65256>, 0xa8023478 <Run+2048>, 0xa8023478 <Run+2048>, 0xa8022fb8 <Run+832>, 0xa8031cb4 <Run+61500>, 0xa8022fb8 <Run+832> <repeats 14 times>, 
          0xa8031ce0 <Run+61544>, 0xa8031d94 <Run+61724>, 0xa8032c00 <Run+65416>, 0xa8031588 <Run+59664>, 0xa803163c <Run+59844>, 0xa80316f0 <Run+60024>, 0xa80317a4 <Run+60204>, 0xa803185c <Run+60388>, 0xa803191c <Run+60580>, 
          0xa8031b4c <Run+61140>, 0xa8031c00 <Run+61320>, 0xa8030890 <Run+56344>, 0xa8030944 <Run+56524>, 0xa80309fc <Run+56708>, 0xa8030ab4 <Run+56892>, 0xa8030b6c <Run+57076>, 0xa8030380 <Run+55048>, 0xa803044c <Run+55252>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa80313e0 <Run+59240>, 0xa8031160 <Run+58600>, 0xa80312a0 <Run+58920>, 0xa8030c64 <Run+57324>, 0xa8030da4 <Run+57644>, 0xa8030ef4 <Run+57980>, 0xa8031044 <Run+58316>, 
          0xa8030600 <Run+55688>, 0xa8030740 <Run+56008>, 0xa8035230 <Run+75192>, 0xa8035488 <Run+75792>, 0xa80355d8 <Run+76128>, 0xa8035838 <Run+76736>, 0xa803590c <Run+76948>, 0xa80359d8 <Run+77152>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8034344 <Run+71372>, 0xa8034540 <Run+71880>, 0xa8034620 <Run+72104>, 0xa8034700 <Run+72328>, 0xa80347c8 <Run+72528>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8034944 <Run+72908>, 0xa80349ec <Run+73076>, 0xa8034ac8 <Run+73296>, 0xa8034bfc <Run+73604>, 0xa8022fb8 <Run+832>, 0xa8034cd4 <Run+73820>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8033228 <Run+66992>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8033250 <Run+67032>, 0xa80332f0 <Run+67192>, 
          0xa8030c30 <Run+57272>, 0xa80305cc <Run+55636>, 0xa8031b18 <Run+61088>, 0xa8031ab0 <Run+60984>, 0xa8031ae4 <Run+61036>, 0xa80319d0 <Run+60760>, 0xa8031a04 <Run+60812>, 0xa8031a3c <Run+60868>, 0xa8031a7c <Run+60932>, 
          0xa8031520 <Run+59560>, 0xa8031554 <Run+59612>, 0xa802f7d0 <Run+52056>, 0xa802f804 <Run+52108>, 0xa802f83c <Run+52164>, 0xa802f874 <Run+52220>, 0xa802f8ac <Run+52276>, 0xa802f8f0 <Run+52344>, 0xa802f994 <Run+52508>, 
          0xa802fa38 <Run+52672>, 0xa802fadc <Run+52836>, 0xa802fb80 <Run+53000>, 0xa802fc24 <Run+53164>, 0xa802fcc8 <Run+53328>, 0xa802fd7c <Run+53508>, 0xa802fe2c <Run+53684>, 0xa802fed0 <Run+53848>, 0xa802ff74 <Run+54012>, 
          0xa8030018 <Run+54176>, 0xa80300bc <Run+54340>, 0xa8030164 <Run+54508>, 0xa8030210 <Run+54680>, 0xa80302c8 <Run+54864>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa80375d8 <Run+84320>, 0xa8037514 <Run+84124>, 
          0xa802354c <Run+2260>, 0xa802354c <Run+2260>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa80327f0 <Run+64376>, 0xa80233b4 <Run+1852>, 0xa80233b4 <Run+1852>, 
          0xa8034ff8 <Run+74624>, 0xa8035098 <Run+74784>, 0xa8034dd4 <Run+74076>, 0xa8034e68 <Run+74224>, 0xa8022fb8 <Run+832>, 0xa8034f28 <Run+74416>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8035150 <Run+74968>, 
          0xa8034090 <Run+70680>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8033e80 <Run+70152>, 0xa8034274 <Run+71164>, 0xa8033f30 <Run+70328>, 0xa8033fe0 <Run+70504>, 0xa8034130 <Run+70840>, 0xa803350c <Run+67732>, 
          0xa80335ac <Run+67892>, 0xa8033674 <Run+68092>, 0xa8033738 <Run+68288>, 0xa8022fb8 <Run+832>, 0xa80337f8 <Run+68480>, 0xa80338a0 <Run+68648>, 0xa803394c <Run+68820>, 0xa8033a9c <Run+69156>, 0xa8033b5c <Run+69348>, 
          0xa8033b60 <Run+69352>, 0xa8033b64 <Run+69356>, 0xa8033b68 <Run+69360>, 0xa8033b6c <Run+69364>, 0xa8033b70 <Run+69368>, 0xa8022cd0 <Run+88>, 0xa8022cd0 <Run+88>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>...}
        opcodes66 = {0xa8022fb8 <Run+832>, 0xa8023770 <Run+2808>, 0xa8022fb8 <Run+832>, 0xa8025cbc <Run+12356>, 0xa8022fb8 <Run+832>, 0xa8025d78 <Run+12544>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa8025878 <Run+11264>, 0xa8022fb8 <Run+832>, 0xa802592c <Run+11444>, 0xa8022fb8 <Run+832>, 0xa80240cc <Run+5204>, 0xa8022fb8 <Run+832>, 0xa80240b4 <Run+5180>, 0xa8022fb8 <Run+832>, 0xa8024100 <Run+5256>, 
          0xa8022fb8 <Run+832>, 0xa8024008 <Run+5008>, 0xa8022fb8 <Run+832>, 0xa80243f8 <Run+6016>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8024318 <Run+5792>, 0xa8022fb8 <Run+832>, 0xa8024424 <Run+6060>, 
          0xa8022fb8 <Run+832>, 0xa802edd4 <Run+49500>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802ee00 <Run+49544>, 0xa8022fb8 <Run+832>, 0xa8023a9c <Run+3620>, 0xa8022fb8 <Run+832>, 0xa8023b50 <Run+3800>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8023b84 <Run+3852>, 0xa8022fb8 <Run+832>, 0xa8023c40 <Run+4040>, 0xa8022fb8 <Run+832>, 0xa8023cfc <Run+4228>, 0xa802dbd4 <Run+44892>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8023d38 <Run+4288>, 0xa8022fb8 <Run+832>, 0xa8023dec <Run+4468>, 0xa8022fb8 <Run+832>, 0xa80243c4 <Run+5964>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802dbf0 <Run+44920>, 
          0xa8022fb8 <Run+832>, 0xa802afa4 <Run+33580>, 0xa8022fb8 <Run+832>, 0xa802b04c <Run+33748>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802b074 <Run+33788>, 0xa802b078 <Run+33792>, 0xa802b07c <Run+33796>, 
          0xa802b080 <Run+33800>, 0xa802b084 <Run+33804>, 0xa802b088 <Run+33808>, 0xa8022de8 <Run+368>, 0xa8022de8 <Run+368>, 0xa802b08c <Run+33812>, 0xa802ae90 <Run+33304>, 0xa802ae94 <Run+33308>, 0xa802ae98 <Run+33312>, 
          0xa802ae9c <Run+33316>, 0xa802aea0 <Run+33320>, 0xa8022da8 <Run+304>, 0xa8022da8 <Run+304>, 0xa802aea4 <Run+33324>, 0xa802aea8 <Run+33328>, 0xa802aeac <Run+33332>, 0xa802aeb0 <Run+33336>, 0xa802aeb4 <Run+33340>, 
          0xa802aeb8 <Run+33344>, 0xa8022d78 <Run+256>, 0xa8022d78 <Run+256>, 0xa802aebc <Run+33348>, 0xa802aec0 <Run+33352>, 0xa802aec4 <Run+33356>, 0xa802aec8 <Run+33360>, 0xa802aecc <Run+33364>, 0xa802aed0 <Run+33368>, 
          0xa8022d48 <Run+208>, 0xa8022d48 <Run+208>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802300c <Run+916>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa802aed4 <Run+33372>, 0xa802af7c <Run+33540>, 0xa802e018 <Run+45984>, 0xa8022fb8 <Run+832> <repeats 21 times>, 0xa8023254 <Run+1500>, 0xa8022fb8 <Run+832>, 0xa8023254 <Run+1500>, 0xa8022fb8 <Run+832>, 
          0xa802dd88 <Run+45328>, 0xa8022fb8 <Run+832>, 0xa802de30 <Run+45496>, 0xa8022fb8 <Run+832>, 0xa802ded8 <Run+45664>, 0xa8022fb8 <Run+832>, 0xa802df78 <Run+45824>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa802dcd0 <Run+45144>, 0xa802dd6c <Run+45300>, 0xa8022fb8 <Run+832>, 0xa802a35c <Run+30436>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa802a388 <Run+30480>, 0xa802a3ac <Run+30516>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802a3d8 <Run+30560>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa802a414 <Run+30620>, 0xa8022fb8 <Run+832>, 0xa802a438 <Run+30656>, 0xa8022fb8 <Run+832>, 0xa802a45c <Run+30692>, 0xa8022fb8 <Run+832>, 0xa802a4ac <Run+30772>, 0xa8022fb8 <Run+832>, 0xa802a500 <Run+30856>, 
          0xa8022fb8 <Run+832>, 0xa802a528 <Run+30896>, 0xa8022fb8 <Run+832>, 0xa802a56c <Run+30964>, 0xa8022fb8 <Run+832>, 0xa802a5a8 <Run+31024>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802a5f4 <Run+31100>, 0xa802a5f8 <Run+31104>, 0xa802a5fc <Run+31108>, 0xa802a600 <Run+31112>, 0xa8024848 <Run+7120>, 
          0xa802484c <Run+7124>, 0xa8022d20 <Run+168>, 0xa8022d20 <Run+168>, 0xa8022fb8 <Run+832>, 0xa8024850 <Run+7128>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa8024908 <Run+7312>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa80232dc <Run+1636>, 0xa8022fb8 <Run+832>...}
        opcodes660f = {0xa8022fb8 <Run+832> <repeats 16 times>, 0xa8028820 <Run+23464>, 0xa8027364 <Run+18156>, 0xa8028b28 <Run+24240>, 0xa802899c <Run+23844>, 0xa8028a48 <Run+24016>, 0xa8026d1c <Run+16548>, 0xa8028cc0 <Run+24648>, 
          0xa8028bd4 <Run+24412>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8028c7c <Run+24580>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8027920 <Run+19624>, 0xa8028fac <Run+25396>, 0xa8028d6c <Run+24820>, 
          0xa8022fb8 <Run+832>, 0xa8028e80 <Run+25096>, 0xa8024994 <Run+7452>, 0xa8023048 <Run+976>, 0xa8023048 <Run+976>, 0xa8022fb8 <Run+832> <repeats 16 times>, 0xa8024638 <Run+6592>, 0xa8023f54 <Run+4828>, 0xa80244d0 <Run+6232>, 
          0xa8024264 <Run+5612>, 0xa8024584 <Run+6412>, 0xa8023ea0 <Run+4648>, 0xa80241ac <Run+5428>, 0xa80282a0 <Run+22056>, 0xa8028360 <Run+22248>, 0xa8027610 <Run+18840>, 0xa80286a8 <Run+23088>, 0xa802853c <Run+22724>, 
          0xa80285f0 <Run+22904>, 0xa8026724 <Run+15020>, 0xa80288e4 <Run+23660>, 0xa802875c <Run+23268>, 0xa8024b78 <Run+7936>, 0xa80253cc <Run+10068>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8025538 <Run+10432>, 
          0xa8024a34 <Run+7612>, 0xa802567c <Run+10756>, 0xa802512c <Run+9396>, 0xa8025270 <Run+9720>, 0xa80262bc <Run+13892>, 0xa8026e0c <Run+16788>, 0xa80267dc <Run+15204>, 0xa8029edc <Run+29284>, 0xa8027428 <Run+18352>, 
          0xa802a038 <Run+29632>, 0xa802653c <Run+14532>, 0xa80292cc <Run+26196>, 0xa80290d4 <Run+25692>, 0xa80291e4 <Run+25964>, 0xa802700c <Run+17300>, 0xa8029714 <Run+27292>, 0xa80293e4 <Run+26476>, 0xa80295b4 <Run+26940>, 
          0xa80269c4 <Run+15692>, 0xa8029b2c <Run+28340>, 0xa8029944 <Run+27852>, 0xa8029a54 <Run+28124>, 0xa80276c4 <Run+19020>, 0xa8029dfc <Run+29060>, 0xa8029c4c <Run+28628>, 0xa8029d3c <Run+28868>, 0xa8026418 <Run+14240>, 
          0xa8027c00 <Run+20360>, 0xa8027a44 <Run+19916>, 0xa8027b08 <Run+20112>, 0xa8026f58 <Run+17120>, 0xa8028080 <Run+21512>, 0xa8027d70 <Run+20728>, 0xa8027f20 <Run+21160>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8026920 <Run+15528>, 0xa8028414 <Run+22428>, 0xa8022fb8 <Run+832> <repeats 35 times>, 0xa802478c <Run+6932>, 
          0xa8023144 <Run+1228>, 0xa8023144 <Run+1228>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8024c2c <Run+8116>, 0xa80231cc <Run+1364>, 0xa80231cc <Run+1364>, 
--Type <RET> for more, q to quit, c to continue without paging--
          0xa8022fb8 <Run+832>, 0xa8025f68 <Run+13040>, 0xa8022fb8 <Run+832>, 0xa802601c <Run+13220>, 0xa8022fb8 <Run+832>, 0xa802c2e8 <Run+38512>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802c798 <Run+39712>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802c0d8 <Run+37984>, 0xa802c830 <Run+39864>, 0xa802c594 <Run+39196>, 0xa802c8e0 <Run+40040>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8025de4 <Run+12652>, 0xa8025ea8 <Run+12848>, 0xa8022fb8 <Run+832>, 0xa802b090 <Run+33816>, 0xa802b134 <Run+33980>, 0xa802b1e0 <Run+34152>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802b310 <Run+34456>, 0xa802b414 <Run+34716>, 
          0xa802b518 <Run+34976>, 0xa802b61c <Run+35236>, 0xa802b75c <Run+35556>, 0xa802b8cc <Run+35924>, 0xa802b9b0 <Run+36152>, 0xa802bb94 <Run+36636>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802c1a4 <Run+38188>, 
          0xa802beb8 <Run+37440>, 0xa8022fb8 <Run+832>, 0xa802c3b8 <Run+38720>, 0xa802bd74 <Run+37116>, 0xa8022fb8 <Run+832>, 0xa802c644 <Run+39372>, 0xa802eb30 <Run+48824>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 
          0xa802ec44 <Run+49100>, 0xa802e0c0 <Run+46152>, 0xa8022fb8 <Run+832>, 0xa802e208 <Run+46480>, 0xa8022fb8 <Run+832>, 0xa8022fb8 <Run+832>, 0xa802e5dc <Run+47460>, 0xa802e71c <Run+47780>...}
        i = <optimized out>
        i = <optimized out>
        i = <optimized out>
        sib = <optimized out>
        base = <optimized out>
        base = <optimized out>
        sib = <optimized out>
#5  0xa8006bd4 in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /home/pi/box86/src/main.c:425
        context = 0xa80c9150
        p = <optimized out>
        prog = <optimized out>
        f = <optimized out>
        elf_header = 0xa80ccb28
        mainelf = <optimized out>
        ret = <optimized out>
```

**Comment by ptitSeb** [comment]
Ah, I see. Thanks for the trace, it should be fixed now.

**Comment by ITotalJustice** [comment]
Thanks, got further now, getting a few new errors before the seg fault
```
NecroDancer version v1.29 loading...
OnCreate: Initializing Steam
GoG: Initializing galaxy API1
GoG: Initializing galaxy API2
Error: unimplemented dl_iterate_phdr(0xb6509e40, 0xb6c59c58) used
AL lib: (EE) alc_cleanup: 1 device not closed
Segmentation fault
```
and the bt didn't provide much info
```
Thread 4 "box86" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb1631450 (LWP 8392)]
0xb64724e0 in ?? ()
(gdb) bt
#0  0xb64724e0 in ?? ()
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
and last few lines from the box86-debug
```
8460|0x8081e9a: Calling memmove (A9008760, A90DD310, 00000080...) => return 0xA9008760
8460|0xb65e06d8: Calling free (A90DD310, 00000000, 00000000...) => return 0xA90DD310
8460|0x81e1d2a: Calling fwrite (A9008760, 00000001, 00000082...) => return 0x00000082
8460|0xb65e06d8: Calling free (A9008760, B65E06C6, B6CB3EFC...) => return 0x00000082
8460|0x81e1d51: Calling fclose (A8ED1990, 00000001, 00000082...) => return 0x00000000
8460|0x81e4bcd: Calling free (A90DC4A0, B6CB3FD0, B6CB3FD4...) => return 0x00000092
8460|0x81e4bdc: Calling free (A90DC258, B6CB3FD0, B6CB3FD4...) => return 0x0000008E
8460|0x81e4beb: Calling free (A90DC038, B6CB3FD0, B6CB3FD4...) => return 0x00000085
8460|0x81e4bfa: Calling free (A90DBE18, B6CB3FD0, B6CB3FD4...) => return 0x00000084
8460|0x81e4c09: Calling free (A90DBA10, B6CB3FD0, B6CB3FD4...) => return 0x00000079
8460|0x81e4c27: Calling free (A90BB680, B6CB3FD0, B6CB3FD4...) => return 0x00000015
8460|0x81e4c36: Calling free (A90D9988, B6CB3FD0, B6CB3FD4...) => return 0x0000000B
8460|0x81e4c45: Calling free (A90B5EC8, B6CB3FD0, B6CB3FD4...) => return 0x00000001
8460|0x81e4c54: Calling free (A90D99C0, B6CB3FD0, B6CB3FD4...) => return 0x00000004
8460|0x830be22: Calling free (A90DD270, 00000001, A90B5EC8...) => return 0x0000001D
8460|0xb65e0ced: Calling malloc (00000064, 084C7E00, A90BB680...) => return 0xA8FDBDB0
8460|0xb65e129b: Calling ___tls_get_addr (00000064, B65E1286, B66E7000...) => return 0xA8FEE360
8460|0xb6565130: Calling dl_iterate_phdr (B6563E40, B6CB3C58, 00000100...) =>Error: unimplemented dl_iterate_phdr(0xb6563e40, 0xb6cb3c58) used
 return 0x00000000
Emulation finished, EAX=0
Free a X86 Emu (0xa8ed1af8)
AL lib: (EE) alc_cleanup: 1 device not closed
Free a X86 Emu (0xa90db208)
```

**Comment by ptitSeb** [comment]
Mmmm, most of the time, `dl_iterate_phdr` is used in signal catcher. Maybe try to run it with `BOX86_NOSIGSEGV=1` to prevent the software to install a segfault signal handler.
If it was the case, there should still be a segfault, but in the real location.
If it's not the case, nothing will have changed and the actual `dl_iterate_phdr` function is needed.

**Comment by ptitSeb** [comment]
Also, maybe it's the GoG Galaxy runtime, and removing the galaxy libs may also be enough?

**Comment by ITotalJustice** [comment]
Sadly adding `BOX86_NOSIGSEGV=1` didn't change anything in the output, debugs or gdb bt.

I've looked and i couldn't see anything regarding gog galaxy. The few libs i didn't recognize i did check to see what they were, but they were nothing to do with gog

**Comment by ptitSeb** [comment]
Ah ok.
I'll need to add some implementation of `dl_iterate_phdr`
I should be able to do a basic implementation, probably not complete, but hopefully complete enough...

**Comment by ptitSeb** [comment]
Crypt of the Necrodancer is working now. Can I close the ticket?
