### ISSUE TITLE
Baba is you: fails to boot, lots of missing symbols

### ISSUE THREAD

**Issue by ITotalJustice** [ptitSeb/box86#41]
Heres the full output from running box86.
```
BOX86_LD_LIBRARY_PATH=.:lib:lib/lib:x86:lib32:/usr/i686-linux-gnu/lib:/usr/lib/arm-linux-gnueabihf box86 Chowdren 
BOX86_LD_LIBRARY_PATH: ./:lib/:lib/lib/:x86/:lib32/:/usr/i686-linux-gnu/lib/:/usr/lib/arm-linux-gnueabihf/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for Chowdren
Using native(wrapped) libGL.so.1
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libm.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using native(wrapped) libX11.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
SDL could not be initialized: No available video device
Opening audio device
Using emulated /usr/i686-linux-gnu/lib/libpulse-simple.so.0
Using emulated /usr/i686-linux-gnu/lib/libpulse.so.0
Using emulated /usr/i686-linux-gnu/lib/libpulsecommon-12.2.so
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libxcb.so.1
Using emulated /usr/i686-linux-gnu/lib/libICE.so.6
Using emulated /usr/i686-linux-gnu/lib/libbsd.so.0
Using emulated /usr/i686-linux-gnu/lib/libSM.so.6
Using native(wrapped) libuuid.so.1
Using emulated /usr/i686-linux-gnu/lib/libXtst.so.6
Using emulated /usr/i686-linux-gnu/lib/libsystemd.so.0
Using emulated /usr/i686-linux-gnu/lib/liblzma.so.5
Using emulated /usr/i686-linux-gnu/lib/liblz4.so.1
Using emulated /usr/i686-linux-gnu/lib/libgcrypt.so.20
Using emulated /usr/i686-linux-gnu/lib/libgpg-error.so.0
Using emulated /usr/i686-linux-gnu/lib/libwrap.so.0
Using emulated /usr/i686-linux-gnu/lib/libnsl.so.1
Using emulated /usr/i686-linux-gnu/lib/libsndfile.so.1
Using emulated /usr/i686-linux-gnu/lib/libFLAC.so.8
Using native(wrapped) libogg.so.0
Using native(wrapped) libvorbis.so.0
Using emulated /usr/i686-linux-gnu/lib/libvorbisenc.so.2
Using emulated /usr/i686-linux-gnu/lib/libasyncns.so.0
Using native(wrapped) libresolv.so.2
Using native(wrapped) libdbus-1.so.3
Using emulated /usr/i686-linux-gnu/lib/libcap.so.2
Error: Symbol warnx not found, cannot apply R_386_JMP_SLOT @0xb64b3ef0 (0x34b6)
Error: Symbol fopencookie not found, cannot apply R_386_JMP_SLOT @0xb64b3f28 (0x3596)
Error: Symbol vwarn not found, cannot apply R_386_JMP_SLOT @0xb64b3f2c (0x35a6)
Error: Symbol __explicit_bzero_chk not found, cannot apply R_386_JMP_SLOT @0xb64b3f5c (0x3666)
Error: Symbol _XDeqAsyncHandler not found, cannot apply R_386_JMP_SLOT @0xb6eb3034 (0xe06)
Error: Symbol _XGetAsyncData not found, cannot apply R_386_JMP_SLOT @0xb6eb3054 (0xe86)
Error: Symbol memfd_create not found, cannot apply R_386_JMP_SLOT @0xb6466a08 (0xb1c6)
Error: Symbol __ppoll_chk not found, cannot apply R_386_JMP_SLOT @0xb6466a2c (0xb256)
Error: Symbol mq_getattr not found, cannot apply R_386_JMP_SLOT @0xb6466a78 (0xb386)
Error: Symbol setns not found, cannot apply R_386_JMP_SLOT @0xb6466b40 (0xb6a6)
Error: Symbol signalfd not found, cannot apply R_386_JMP_SLOT @0xb6466ba0 (0xb826)
Error: Symbol sigisemptyset not found, cannot apply R_386_JMP_SLOT @0xb6466bfc (0xb996)
Error: Symbol timerfd_create not found, cannot apply R_386_JMP_SLOT @0xb6466c64 (0xbb36)
Error: Symbol parse_printf_format not found, cannot apply R_386_JMP_SLOT @0xb6466cfc (0xbd96)
Error: Symbol mempcpy not found, cannot apply R_386_JMP_SLOT @0xb6466de8 (0xc146)
Error: Symbol open_memstream not found, cannot apply R_386_JMP_SLOT @0xb6466e68 (0xc346)
Error: Symbol timerfd_settime not found, cannot apply R_386_JMP_SLOT @0xb6466e94 (0xc3f6)
Warning, don't know of to handle rel #2 type: R_386_TLS_TPOFF (0xb6265fc8)
Error: Global Symbol xdr_u_int not found, cannot apply R_386_GLOB_DAT @0xb6265fd4 ((nil))
Error: Global Symbol xdr_void not found, cannot apply R_386_GLOB_DAT @0xb6265fe4 ((nil))
Error: Global Symbol xdr_bool not found, cannot apply R_386_GLOB_DAT @0xb6265fe8 ((nil))
Error: Global Symbol _libc_intl_domainname not found, cannot apply R_386_GLOB_DAT @0xb6265fec ((nil))
Error: Global Symbol __pthread_once not found, cannot apply R_386_GLOB_DAT @0xb6265ff0 ((nil))
Error: Global Symbol xdr_netobj not found, cannot apply R_386_GLOB_DAT @0xb6265ff8 ((nil))
Error: Symbol xdr_string not found, cannot apply R_386_JMP_SLOT @0xb626600c (0x3046)
Error: Symbol clnt_pcreateerror not found, cannot apply R_386_JMP_SLOT @0xb6266018 (0x3076)
Error: Symbol svc_register not found, cannot apply R_386_JMP_SLOT @0xb6266020 (0x3096)
Error: Symbol svcudp_bufcreate not found, cannot apply R_386_JMP_SLOT @0xb6266030 (0x30d6)
Error: Symbol __asprintf not found, cannot apply R_386_JMP_SLOT @0xb6266038 (0x30f6)
Error: Symbol key_gendes not found, cannot apply R_386_JMP_SLOT @0xb6266060 (0x3196)
Error: Symbol xdr_pointer not found, cannot apply R_386_JMP_SLOT @0xb6266068 (0x31b6)
Error: Symbol xprt_unregister not found, cannot apply R_386_JMP_SLOT @0xb6266070 (0x31d6)
Error: Symbol svctcp_create not found, cannot apply R_386_JMP_SLOT @0xb6266078 (0x31f6)
Error: Symbol xdrmem_create not found, cannot apply R_386_JMP_SLOT @0xb6266080 (0x3216)
Error: Symbol xdr_enum not found, cannot apply R_386_JMP_SLOT @0xb6266088 (0x3236)
Error: Symbol xdr_sizeof not found, cannot apply R_386_JMP_SLOT @0xb62660ac (0x32c6)
Error: Symbol __libc_clntudp_bufcreate not found, cannot apply R_386_JMP_SLOT @0xb62660b4 (0x32e6)
Error: Symbol xdr_u_char not found, cannot apply R_386_JMP_SLOT @0xb62660c4 (0x3326)
Error: Symbol xdr_free not found, cannot apply R_386_JMP_SLOT @0xb62660cc (0x3346)
Error: Symbol authdes_pk_create not found, cannot apply R_386_JMP_SLOT @0xb62660d4 (0x3366)
Error: Symbol xdr_array not found, cannot apply R_386_JMP_SLOT @0xb62660d8 (0x3376)
Error: Symbol __libc_rpc_getport not found, cannot apply R_386_JMP_SLOT @0xb62660e0 (0x3396)
Error: Symbol xdr_uint32_t not found, cannot apply R_386_JMP_SLOT @0xb62660e4 (0x33a6)
Error: Symbol authdes_create not found, cannot apply R_386_JMP_SLOT @0xb62660f4 (0x33e6)
Error: Symbol key_secretkey_is_set not found, cannot apply R_386_JMP_SLOT @0xb62660f8 (0x33f6)
Error: Symbol asprintf not found, cannot apply R_386_JMP_SLOT @0xb62660fc (0x3406)
Error: Symbol svc_sendreply not found, cannot apply R_386_JMP_SLOT @0xb6266104 (0x3426)
Error: Symbol __mempcpy not found, cannot apply R_386_JMP_SLOT @0xb6266108 (0x3436)
Error: Symbol clntudp_create not found, cannot apply R_386_JMP_SLOT @0xb626610c (0x3446)
Error: Symbol clnt_perror not found, cannot apply R_386_JMP_SLOT @0xb6266110 (0x3456)
Error: Symbol authunix_create_default not found, cannot apply R_386_JMP_SLOT @0xb6266114 (0x3466)
Error: Symbol __nss_hash not found, cannot apply R_386_JMP_SLOT @0xb6266118 (0x3476)
Error: Symbol clnt_create not found, cannot apply R_386_JMP_SLOT @0xb6266120 (0x3496)
Error: Symbol __rpc_thread_svc_max_pollfd not found, cannot apply R_386_JMP_SLOT @0xb6266128 (0x34b6)
Error: Symbol host2netname not found, cannot apply R_386_JMP_SLOT @0xb626612c (0x34c6)
Error: Symbol xdr_opaque not found, cannot apply R_386_JMP_SLOT @0xb6266130 (0x34d6)
Error: Symbol svcerr_systemerr not found, cannot apply R_386_JMP_SLOT @0xb626613c (0x3506)
Error: Symbol rawmemchr not found, cannot apply R_386_JMP_SLOT @0xb6266140 (0x3516)
Error: Symbol xdr_int not found, cannot apply R_386_JMP_SLOT @0xb6266148 (0x3536)
Error: Symbol svcerr_noproc not found, cannot apply R_386_JMP_SLOT @0xb626614c (0x3546)
Error: Symbol get_myaddress not found, cannot apply R_386_JMP_SLOT @0xb6266154 (0x3566)
Error: Symbol svcerr_decode not found, cannot apply R_386_JMP_SLOT @0xb6266158 (0x3576)
Error: Symbol xdrstdio_create not found, cannot apply R_386_JMP_SLOT @0xb626615c (0x3586)
Error: Symbol __rpc_thread_svc_pollfd not found, cannot apply R_386_JMP_SLOT @0xb6266168 (0x35b6)
Error: Symbol __stpcpy not found, cannot apply R_386_JMP_SLOT @0xb6266170 (0x35d6)
Error: Symbol clnttcp_create not found, cannot apply R_386_JMP_SLOT @0xb6266178 (0x35f6)
Error: Symbol xdr_bytes not found, cannot apply R_386_JMP_SLOT @0xb6266180 (0x3616)
Error: Symbol svc_getreq_poll not found, cannot apply R_386_JMP_SLOT @0xb626618c (0x3646)
Error: Symbol innetgr not found, cannot apply R_386_JMP_SLOT @0xb6494f28 (0x2496)
Error: Symbol capset not found, cannot apply R_386_JMP_SLOT @0xb615af88 (0x10a6)
Error: Symbol capget not found, cannot apply R_386_JMP_SLOT @0xb615af90 (0x10c6)
Error: Symbol asprintf not found, cannot apply R_386_JMP_SLOT @0xb615afa8 (0x1126)
Error: Global Symbol g_get_application_name not found, cannot apply R_386_GLOB_DAT @0xb6573fbc ((nil))
Error: Global Symbol gtk_window_get_default_icon_name not found, cannot apply R_386_GLOB_DAT @0xb6573fcc ((nil))
Error: Global Symbol in6addr_loopback not found, cannot apply R_386_GLOB_DAT @0xb6573fd8 ((nil))
Error: Global Symbol gdk_display not found, cannot apply R_386_GLOB_DAT @0xb6573ff8 ((nil))
Error: Global Symbol main not found, cannot apply R_386_GLOB_DAT @0xb6573ffc ((nil))
Error: Symbol dbus_free not found, cannot apply R_386_JMP_SLOT @0xb657346c (0xe2e6)
Error: Symbol xcb_connection_has_error not found, cannot apply R_386_JMP_SLOT @0xb6573470 (0xe2f6)
Error: Symbol dbus_message_iter_get_fixed_array not found, cannot apply R_386_JMP_SLOT @0xb65734a0 (0xe3b6)
Error: Symbol dbus_message_iter_recurse not found, cannot apply R_386_JMP_SLOT @0xb65734d0 (0xe476)
Error: Symbol dbus_message_iter_append_fixed_array not found, cannot apply R_386_JMP_SLOT @0xb65734e4 (0xe4c6)
Error: Symbol xcb_intern_atom not found, cannot apply R_386_JMP_SLOT @0xb6573564 (0xe6c6)
Error: Symbol dbus_watch_get_flags not found, cannot apply R_386_JMP_SLOT @0xb657361c (0xe9a6)
Error: Symbol dbus_message_iter_get_signature not found, cannot apply R_386_JMP_SLOT @0xb6573664 (0xeac6)
Error: Symbol dbus_message_iter_append_basic not found, cannot apply R_386_JMP_SLOT @0xb657367c (0xeb26)
Error: Symbol dbus_connection_send not found, cannot apply R_386_JMP_SLOT @0xb65736f8 (0xed16)
Error: Symbol xcb_connect not found, cannot apply R_386_JMP_SLOT @0xb6573754 (0xee86)
Error: Symbol xcb_setup_roots_iterator not found, cannot apply R_386_JMP_SLOT @0xb65737bc (0xf026)
Error: Symbol xcb_get_property not found, cannot apply R_386_JMP_SLOT @0xb65737f0 (0xf0f6)
Error: Symbol dbus_message_append_args not found, cannot apply R_386_JMP_SLOT @0xb65737f4 (0xf106)
Error: Symbol dbus_connection_set_wakeup_main_function not found, cannot apply R_386_JMP_SLOT @0xb6573804 (0xf146)
Error: Symbol gethostid not found, cannot apply R_386_JMP_SLOT @0xb6573830 (0xf1f6)
Error: Symbol dbus_connection_set_watch_functions not found, cannot apply R_386_JMP_SLOT @0xb6573834 (0xf206)
Error: Symbol dbus_pending_call_unref not found, cannot apply R_386_JMP_SLOT @0xb6573840 (0xf236)
Error: Symbol dbus_message_new_error not found, cannot apply R_386_JMP_SLOT @0xb6573868 (0xf2d6)
Error: Symbol dbus_watch_handle not found, cannot apply R_386_JMP_SLOT @0xb6573874 (0xf306)
Error: Symbol dbus_message_new_method_call not found, cannot apply R_386_JMP_SLOT @0xb6573888 (0xf356)
Error: Symbol xcb_get_setup not found, cannot apply R_386_JMP_SLOT @0xb65738bc (0xf426)
Error: Symbol dbus_watch_set_data not found, cannot apply R_386_JMP_SLOT @0xb65738f0 (0xf4f6)
Error: Symbol dbus_watch_get_unix_fd not found, cannot apply R_386_JMP_SLOT @0xb65738fc (0xf526)
Error: Symbol memfd_create not found, cannot apply R_386_JMP_SLOT @0xb657390c (0xf566)
Error: Symbol llrint not found, cannot apply R_386_JMP_SLOT @0xb6573920 (0xf5b6)
Error: Symbol dbus_message_iter_next not found, cannot apply R_386_JMP_SLOT @0xb6573928 (0xf5d6)
Error: Symbol dbus_message_unref not found, cannot apply R_386_JMP_SLOT @0xb6573930 (0xf5f6)
Error: Symbol dbus_connection_set_dispatch_status_function not found, cannot apply R_386_JMP_SLOT @0xb65739b8 (0xf816)
Error: Symbol dbus_connection_read_write_dispatch not found, cannot apply R_386_JMP_SLOT @0xb65739d8 (0xf896)
Error: Symbol dbus_message_iter_open_container not found, cannot apply R_386_JMP_SLOT @0xb65739fc (0xf926)
Error: Symbol xcb_intern_atom_reply not found, cannot apply R_386_JMP_SLOT @0xb6573a00 (0xf936)
Error: Symbol dbus_connection_send_with_reply_and_block not found, cannot apply R_386_JMP_SLOT @0xb6573a08 (0xf956)
Error: Symbol xcb_get_property_value not found, cannot apply R_386_JMP_SLOT @0xb6573a60 (0xfab6)
Error: Symbol dbus_watch_get_data not found, cannot apply R_386_JMP_SLOT @0xb6573acc (0xfc66)
Error: Symbol posix_madvise not found, cannot apply R_386_JMP_SLOT @0xb6573b20 (0xfdb6)
Error: Symbol xcb_get_property_reply not found, cannot apply R_386_JMP_SLOT @0xb6573b64 (0xfec6)
Error: Symbol dbus_message_new_method_return not found, cannot apply R_386_JMP_SLOT @0xb6573bb8 (0x10016)
Error: Symbol dbus_message_iter_close_container not found, cannot apply R_386_JMP_SLOT @0xb6573be0 (0x100b6)
Error: Symbol dbus_error_init not found, cannot apply R_386_JMP_SLOT @0xb6573be4 (0x100c6)
Error: Symbol dbus_type_is_basic not found, cannot apply R_386_JMP_SLOT @0xb6573c14 (0x10186)
Error: Symbol dbus_message_iter_get_arg_type not found, cannot apply R_386_JMP_SLOT @0xb6573c4c (0x10266)
Error: Symbol dbus_pending_call_cancel not found, cannot apply R_386_JMP_SLOT @0xb6573ce0 (0x104b6)
Error: Symbol dbus_connection_dispatch not found, cannot apply R_386_JMP_SLOT @0xb6573d18 (0x10596)
Error: Symbol xcb_change_property not found, cannot apply R_386_JMP_SLOT @0xb6573d24 (0x105c6)
Error: Symbol dbus_watch_get_enabled not found, cannot apply R_386_JMP_SLOT @0xb6573d38 (0x10616)
Error: Symbol xcb_screen_next not found, cannot apply R_386_JMP_SLOT @0xb6573d9c (0x107a6)
Error: Symbol xcb_disconnect not found, cannot apply R_386_JMP_SLOT @0xb6573da8 (0x107d6)
Error: Symbol personality not found, cannot apply R_386_JMP_SLOT @0xb6573db0 (0x107f6)
Error: Symbol dbus_error_is_set not found, cannot apply R_386_JMP_SLOT @0xb6573df0 (0x108f6)
Error: Symbol dbus_message_get_type not found, cannot apply R_386_JMP_SLOT @0xb6573e04 (0x10946)
Error: Symbol xcb_get_property_value_length not found, cannot apply R_386_JMP_SLOT @0xb6573e08 (0x10956)
Error: Symbol dbus_message_get_signature not found, cannot apply R_386_JMP_SLOT @0xb6573e0c (0x10966)
Error: Symbol dbus_error_free not found, cannot apply R_386_JMP_SLOT @0xb6573e20 (0x109b6)
Error: Symbol dbus_connection_ref not found, cannot apply R_386_JMP_SLOT @0xb6573e24 (0x109c6)
Error: Symbol dbus_set_error_from_message not found, cannot apply R_386_JMP_SLOT @0xb6573e80 (0x10b36)
Error: Symbol dbus_connection_get_server_id not found, cannot apply R_386_JMP_SLOT @0xb6573eb0 (0x10bf6)
Error: Symbol dbus_message_get_args not found, cannot apply R_386_JMP_SLOT @0xb6573f30 (0x10df6)
Error: Symbol pa_stream_connect_playback not found, cannot apply R_386_JMP_SLOT @0xb6ef8f40 (0x1056)
Error: Symbol pa_stream_get_sample_spec not found, cannot apply R_386_JMP_SLOT @0xb6ef8f44 (0x1066)
Error: Symbol pa_stream_set_latency_update_callback not found, cannot apply R_386_JMP_SLOT @0xb6ef8f48 (0x1076)
Error: Symbol pa_threaded_mainloop_stop not found, cannot apply R_386_JMP_SLOT @0xb6ef8f4c (0x1086)
Error: Symbol pa_operation_get_state not found, cannot apply R_386_JMP_SLOT @0xb6ef8f54 (0x10a6)
Error: Symbol pa_stream_write not found, cannot apply R_386_JMP_SLOT @0xb6ef8f58 (0x10b6)
Error: Symbol pa_context_connect not found, cannot apply R_386_JMP_SLOT @0xb6ef8f5c (0x10c6)
Error: Symbol pa_context_disconnect not found, cannot apply R_386_JMP_SLOT @0xb6ef8f60 (0x10d6)
Error: Symbol pa_context_get_state not found, cannot apply R_386_JMP_SLOT @0xb6ef8f64 (0x10e6)
Error: Symbol pa_threaded_mainloop_get_api not found, cannot apply R_386_JMP_SLOT @0xb6ef8f6c (0x1106)
Error: Symbol pa_threaded_mainloop_free not found, cannot apply R_386_JMP_SLOT @0xb6ef8f70 (0x1116)
Error: Symbol pa_stream_set_write_callback not found, cannot apply R_386_JMP_SLOT @0xb6ef8f74 (0x1126)
Error: Symbol pa_threaded_mainloop_signal not found, cannot apply R_386_JMP_SLOT @0xb6ef8f78 (0x1136)
Error: Symbol pa_context_unref not found, cannot apply R_386_JMP_SLOT @0xb6ef8f7c (0x1146)
Error: Symbol pa_context_errno not found, cannot apply R_386_JMP_SLOT @0xb6ef8f80 (0x1156)
Error: Symbol pa_threaded_mainloop_unlock not found, cannot apply R_386_JMP_SLOT @0xb6ef8f84 (0x1166)
Error: Symbol pa_stream_unref not found, cannot apply R_386_JMP_SLOT @0xb6ef8f88 (0x1176)
Error: Symbol pa_stream_get_state not found, cannot apply R_386_JMP_SLOT @0xb6ef8f8c (0x1186)
Error: Symbol pa_stream_new not found, cannot apply R_386_JMP_SLOT @0xb6ef8f94 (0x11a6)
Error: Symbol pa_context_new not found, cannot apply R_386_JMP_SLOT @0xb6ef8f98 (0x11b6)
Error: Symbol pa_threaded_mainloop_new not found, cannot apply R_386_JMP_SLOT @0xb6ef8fa0 (0x11d6)
Error: Symbol pa_threaded_mainloop_lock not found, cannot apply R_386_JMP_SLOT @0xb6ef8fa4 (0x11e6)
Error: Symbol pa_stream_set_state_callback not found, cannot apply R_386_JMP_SLOT @0xb6ef8fa8 (0x11f6)
Error: Symbol pa_operation_unref not found, cannot apply R_386_JMP_SLOT @0xb6ef8fb0 (0x1216)
Error: Symbol pa_operation_cancel not found, cannot apply R_386_JMP_SLOT @0xb6ef8fb4 (0x1226)
Error: Symbol pa_threaded_mainloop_wait not found, cannot apply R_386_JMP_SLOT @0xb6ef8fbc (0x1246)
Error: Symbol pa_threaded_mainloop_start not found, cannot apply R_386_JMP_SLOT @0xb6ef8fc4 (0x1266)
Error: Symbol pa_stream_get_latency not found, cannot apply R_386_JMP_SLOT @0xb6ef8fc8 (0x1276)
Error: Symbol pa_context_set_state_callback not found, cannot apply R_386_JMP_SLOT @0xb6ef8fcc (0x1286)
Error: Symbol pa_stream_peek not found, cannot apply R_386_JMP_SLOT @0xb6ef8fd0 (0x1296)
Error: Symbol pa_stream_connect_record not found, cannot apply R_386_JMP_SLOT @0xb6ef8fd4 (0x12a6)
Error: Symbol pa_stream_drop not found, cannot apply R_386_JMP_SLOT @0xb6ef8fd8 (0x12b6)
Error: Symbol pa_stream_writable_size not found, cannot apply R_386_JMP_SLOT @0xb6ef8fdc (0x12c6)
Error: Symbol pa_stream_set_read_callback not found, cannot apply R_386_JMP_SLOT @0xb6ef8fe4 (0x12e6)
Error: Symbol pa_stream_flush not found, cannot apply R_386_JMP_SLOT @0xb6ef8fe8 (0x12f6)
Error: Symbol pa_stream_drain not found, cannot apply R_386_JMP_SLOT @0xb6ef8fec (0x1306)
Error: Symbol pa_stream_connect_playback not found, cannot apply R_386_JMP_SLOT @0xb6efef40 (0x1056)
Error: Symbol pa_stream_get_sample_spec not found, cannot apply R_386_JMP_SLOT @0xb6efef44 (0x1066)
Error: Symbol pa_stream_set_latency_update_callback not found, cannot apply R_386_JMP_SLOT @0xb6efef48 (0x1076)
Error: Symbol pa_threaded_mainloop_stop not found, cannot apply R_386_JMP_SLOT @0xb6efef4c (0x1086)
Error: Symbol pa_operation_get_state not found, cannot apply R_386_JMP_SLOT @0xb6efef54 (0x10a6)
Error: Symbol pa_stream_write not found, cannot apply R_386_JMP_SLOT @0xb6efef58 (0x10b6)
Error: Symbol pa_context_connect not found, cannot apply R_386_JMP_SLOT @0xb6efef5c (0x10c6)
Error: Symbol pa_context_disconnect not found, cannot apply R_386_JMP_SLOT @0xb6efef60 (0x10d6)
Error: Symbol pa_context_get_state not found, cannot apply R_386_JMP_SLOT @0xb6efef64 (0x10e6)
Error: Symbol pa_threaded_mainloop_get_api not found, cannot apply R_386_JMP_SLOT @0xb6efef6c (0x1106)
Error: Symbol pa_threaded_mainloop_free not found, cannot apply R_386_JMP_SLOT @0xb6efef70 (0x1116)
Error: Symbol pa_stream_set_write_callback not found, cannot apply R_386_JMP_SLOT @0xb6efef74 (0x1126)
Error: Symbol pa_threaded_mainloop_signal not found, cannot apply R_386_JMP_SLOT @0xb6efef78 (0x1136)
Error: Symbol pa_context_unref not found, cannot apply R_386_JMP_SLOT @0xb6efef7c (0x1146)
Error: Symbol pa_context_errno not found, cannot apply R_386_JMP_SLOT @0xb6efef80 (0x1156)
Error: Symbol pa_threaded_mainloop_unlock not found, cannot apply R_386_JMP_SLOT @0xb6efef84 (0x1166)
Error: Symbol pa_stream_unref not found, cannot apply R_386_JMP_SLOT @0xb6efef88 (0x1176)
Error: Symbol pa_stream_get_state not found, cannot apply R_386_JMP_SLOT @0xb6efef8c (0x1186)
Error: Symbol pa_stream_new not found, cannot apply R_386_JMP_SLOT @0xb6efef94 (0x11a6)
Error: Symbol pa_context_new not found, cannot apply R_386_JMP_SLOT @0xb6efef98 (0x11b6)
Error: Symbol pa_threaded_mainloop_new not found, cannot apply R_386_JMP_SLOT @0xb6efefa0 (0x11d6)
Error: Symbol pa_threaded_mainloop_lock not found, cannot apply R_386_JMP_SLOT @0xb6efefa4 (0x11e6)
Error: Symbol pa_stream_set_state_callback not found, cannot apply R_386_JMP_SLOT @0xb6efefa8 (0x11f6)
Error: Symbol pa_operation_unref not found, cannot apply R_386_JMP_SLOT @0xb6efefb0 (0x1216)
Error: Symbol pa_operation_cancel not found, cannot apply R_386_JMP_SLOT @0xb6efefb4 (0x1226)
Error: Symbol pa_threaded_mainloop_wait not found, cannot apply R_386_JMP_SLOT @0xb6efefbc (0x1246)
Error: Symbol pa_threaded_mainloop_start not found, cannot apply R_386_JMP_SLOT @0xb6efefc4 (0x1266)
Error: Symbol pa_stream_get_latency not found, cannot apply R_386_JMP_SLOT @0xb6efefc8 (0x1276)
Error: Symbol pa_context_set_state_callback not found, cannot apply R_386_JMP_SLOT @0xb6efefcc (0x1286)
Error: Symbol pa_stream_peek not found, cannot apply R_386_JMP_SLOT @0xb6efefd0 (0x1296)
Error: Symbol pa_stream_connect_record not found, cannot apply R_386_JMP_SLOT @0xb6efefd4 (0x12a6)
Error: Symbol pa_stream_drop not found, cannot apply R_386_JMP_SLOT @0xb6efefd8 (0x12b6)
Error: Symbol pa_stream_writable_size not found, cannot apply R_386_JMP_SLOT @0xb6efefdc (0x12c6)
Error: Symbol pa_stream_set_read_callback not found, cannot apply R_386_JMP_SLOT @0xb6efefe4 (0x12e6)
Error: Symbol pa_stream_flush not found, cannot apply R_386_JMP_SLOT @0xb6efefe8 (0x12f6)
Error: Symbol pa_stream_drain not found, cannot apply R_386_JMP_SLOT @0xb6efefec (0x1306)
Using native(wrapped) libasound.so.2
SDL_OpenAudioDevice failed: No such audio device
Defaulting to dummy device
Audio: dummy 44100 33056 2 1024
Preload audio took 0.000374079
Segmentation fault
```

**Comment by ptitSeb** [comment]
yeah, there are a lot of missing symbol. This game seems to be statically linked to SDL.
But I'm unsure the isue are with the symbols.
At the beggining there is: `SDL could not be initialized: No available video device`
I don't think that's good.
SDL doesn't seem to be able to open Audio device either, falling back to Dummy Audio (but the missing symbol probably didn't help there).

**Comment by ptitSeb** [comment]
I think next step would be to get a `BOX86_LOG=DEBUG` trace. I'm interested in the last line (like ~50) before the "SDL could not be initialized: No available video device" message.

**Comment by ITotalJustice** [comment]
Sure, heres the last few lines before it.
```
15290|0x82ffdf8: Calling memcpy (A9AB53E0, A9AB7188, 00000036...) => return 0xA9AB53E0
15290|0x832541b: Calling dlsym (00000007, 08421336, A9AB7188...) =>Call to dlsym(0x7, "XF86VidModeLockModeSwitch")
 Symbol not found
 return 0x00000000
15290|0x8325438: Calling strlen(0x8421336("XF86VidModeLockModeSwitch")) => return 0x00000019
15290|0x82ff54b: Calling malloc (0000001B, FFFFFFFF, 00000019...) => return 0xA9A934D0
15290|0x82ffdd6: Calling strlen(0x8421336("XF86VidModeLockModeSwitch")) => return 0x00000019
15290|0x82ffdf8: Calling memcpy (A9A934D1, 08421336, 00000019...) => return 0xA9A934D1
15290|0x8325467: Calling dlsym (00000007, A9A934D0, 0000001B...) =>Call to dlsym(0x7, "_XF86VidModeLockModeSwitch")
 Symbol not found
 return 0x00000000
15290|0x82ff654: Calling free (A9A934D0, 08421336, 00000019...) => return 0xA9A934D0
15290|0x832547a: Calling dlerror (A9A934D0, A9A934D0, 0000001B...) => return 0xA9AB7188
15290|0x832fdf2: Calling pthread_getspecific (00000003, 00000000, 00000000...) => return 0xA9AB9390
15290|0x82ffdd6: Calling strlen(0x841986c("Failed loading %s: %s")) => return 0x00000015
15290|0x82ffdf8: Calling memcpy (A9AB52DC, 0841986C, 00000015...) => return 0xA9AB52DC
15290|0x82ffdd6: Calling strlen(0x8421336("XF86VidModeLockModeSwitch")) => return 0x00000019
15290|0x82ffdf8: Calling memcpy (A9AB5360, 08421336, 00000019...) => return 0xA9AB5360
15290|0x82ffdd6: Calling strlen(0xa9ab7188("Symbol "_XF86VidModeLockModeSwitch" not found in 0x7)
")) => return 0x00000036
15290|0x82ffdf8: Calling memcpy (A9AB53E0, A9AB7188, 00000036...) => return 0xA9AB53E0
15290|0x832541b: Calling dlsym (00000008, 08421336, A9AB7188...) =>Call to dlsym(0x8, "XF86VidModeLockModeSwitch")
 return 0xA9AC98C4
15290|0x832541b: Calling dlsym (00000001, 084211F6, 00000000...) =>Call to dlsym(0x1, "XCreateIC")
 return 0xA9AD30B8
15290|0x832541b: Calling dlsym (00000001, 08421200, 00000000...) =>Call to dlsym(0x1, "XGetICValues")
 return 0xA9AD31A8
15290|0x837ae5b: Calling dlclose (00000001, 08421336, 00000000...) =>Call to dlclose(0x1)
 return 0x00000000
15290|0x837ae5b: Calling dlclose (00000002, 08421336, 00000000...) =>Call to dlclose(0x2)
 return 0x00000000
15290|0x837ae5b: Calling dlclose (00000003, 08421336, 00000000...) =>Call to dlclose(0x3)
 return 0x00000000
15290|0x837ae5b: Calling dlclose (00000004, 08421336, 00000000...) =>Call to dlclose(0x4)
 return 0x00000000
15290|0x837ae5b: Calling dlclose (00000005, 08421336, 00000000...) =>Call to dlclose(0x5)
 return 0x00000000
15290|0x837ae5b: Calling dlclose (00000006, 08421336, 00000000...) =>Call to dlclose(0x6)
 return 0x00000000
15290|0x837ae5b: Calling dlclose (00000007, 08421336, 00000000...) =>Call to dlclose(0x7)
 return 0x00000000
15290|0x837ae5b: Calling dlclose (00000008, 08421336, 00000000...) =>Call to dlclose(0x8)
 return 0x00000000
15290|0x83255ef: Calling getenv("SDL_VIDEODRIVER") => return 0x00000000(nil)
15290|0x832fdf2: Calling pthread_getspecific (00000003, 00000000, 00000000...) => return 0xA9AB9390
15290|0x82ffdd6: Calling strlen(0x840ac45("No available video device")) => return 0x00000019
15290|0x82ffdf8: Calling memcpy (A9AB52DC, 0840AC45, 00000019...) => return 0xA9AB52DC
15290|0x832fdf2: Calling pthread_getspecific (00000003, 08421200, 00000000...) => return 0xA9AB9390
15290|0x80f7114: Calling strlen(0x83fa2c8("SDL could not be initialized: ")) => return 0x0000001E
15290|0x83e6196: Calling fwrite (083FA2C8, 00000001, 0000001E...) =>SDL could not be initialized:  return 0x0000001E
15290|0x83e646e: Calling fflush (B6E12D90, 00000001, 00000000...) => return 0x00000000
15290|0x80f7114: Calling strlen(0x861b8e0("No available video device")) => return 0x00000019
15290|0x83e6196: Calling fwrite (0861B8E0, 00000001, 00000019...) =>No available video device return 0x00000019
15290|0x83e646e: Calling fflush (B6E12D90, 00000001, 00000000...) => return 0x00000000
15290|0x83e6196: Calling fwrite (B6CA12EC, 00000001, 00000001...) =>
 return 0x00000001
```
I've uploaded the entire log [here just in case](https://ufile.io/v2hg3fc7).

**Comment by ptitSeb** [comment]
So, I have pushed a change on how dlsym works. Hopefully I haven't broke anything, and SDL will now be able to initialize it's graphics at least.

**Comment by ITotalJustice** [comment]
Sadly i seem to get the exact same error when trying the new build. Same print out to cmd as well.
`SDL could not be initialized: No available video device` still happens.

**Comment by ptitSeb** [comment]
The `BOX86_LOG=DEBUG` should be slightly more detailled now.

**Comment by ITotalJustice** [comment]
Ah okay. This is from the only entry of `SDL could not be initialized` being mentioned
```
20619|0x8325438: Calling strlen(0x8421336("XF86VidModeLockModeSwitch")) => return 0x00000019
20619|0x82ff54b: Calling malloc (0000001B, FFFFFFFF, 00000019...) => return 0xA91E7AF8
20619|0x82ffdd6: Calling strlen(0x8421336("XF86VidModeLockModeSwitch")) => return 0x00000019
20619|0x82ffdf8: Calling memcpy (A91E7AF9, 08421336, 00000019...) => return 0xA91E7AF9
20619|0x8325467: Calling dlsym (00000007, A91E7AF8, 0000001B...) =>Call to dlsym(0x7, "_XF86VidModeLockModeSwitch")
 Symbol not found
 return 0x00000000
20619|0x82ff654: Calling free (A91E7AF8, 08421336, 00000019...) => return 0xA91E7AF8
20619|0x832547a: Calling dlerror (A91E7AF8, A91E7AF8, 0000001B...) => return 0xA91FA8E0
20619|0x832fdf2: Calling pthread_getspecific (00000003, 00000000, 00000000...) => return 0xA91FCA78
20619|0x82ffdd6: Calling strlen(0x841986c("Failed loading %s: %s")) => return 0x00000015
20619|0x82ffdf8: Calling memcpy (A91F89C4, 0841986C, 00000015...) => return 0xA91F89C4
20619|0x82ffdd6: Calling strlen(0x8421336("XF86VidModeLockModeSwitch")) => return 0x00000019
20619|0x82ffdf8: Calling memcpy (A91F8A48, 08421336, 00000019...) => return 0xA91F8A48
20619|0x82ffdd6: Calling strlen(0xa91fa8e0("Symbol "_XF86VidModeLockModeSwitch" not found in 0x7(libXss.so.1)")) => return 0x00000041
20619|0x82ffdf8: Calling memcpy (A91F8AC8, A91FA8E0, 00000041...) => return 0xA91F8AC8
20619|0x832541b: Calling dlsym (00000008, 08421336, A91FA8E0...) =>Call to dlsym(0x8, "XF86VidModeLockModeSwitch")
 return 0xA920D084
20619|0x832541b: Calling dlsym (00000001, 084211F6, 00000000...) =>Call to dlsym(0x1, "XCreateIC")
 return 0xA9216858
20619|0x832541b: Calling dlsym (00000001, 08421200, 00000000...) =>Call to dlsym(0x1, "XGetICValues")
 return 0xA9216948
20619|0x837ae5b: Calling dlclose (00000001, 08421336, 00000000...) =>Call to dlclose(0x1)
 return 0x00000000
20619|0x837ae5b: Calling dlclose (00000002, 08421336, 00000000...) =>Call to dlclose(0x2)
 return 0x00000000
20619|0x837ae5b: Calling dlclose (00000003, 08421336, 00000000...) =>Call to dlclose(0x3)
 return 0x00000000
20619|0x837ae5b: Calling dlclose (00000004, 08421336, 00000000...) =>Call to dlclose(0x4)
 return 0x00000000
20619|0x837ae5b: Calling dlclose (00000005, 08421336, 00000000...) =>Call to dlclose(0x5)
 return 0x00000000
20619|0x837ae5b: Calling dlclose (00000006, 08421336, 00000000...) =>Call to dlclose(0x6)
 return 0x00000000
20619|0x837ae5b: Calling dlclose (00000007, 08421336, 00000000...) =>Call to dlclose(0x7)
 return 0x00000000
20619|0x837ae5b: Calling dlclose (00000008, 08421336, 00000000...) =>Call to dlclose(0x8)
 return 0x00000000
20619|0x83255ef: Calling getenv("SDL_VIDEODRIVER") => return 0x00000000(nil)
20619|0x832fdf2: Calling pthread_getspecific (00000003, 00000000, 00000000...) => return 0xA91FCA78
20619|0x82ffdd6: Calling strlen(0x840ac45("No available video device")) => return 0x00000019
20619|0x82ffdf8: Calling memcpy (A91F89C4, 0840AC45, 00000019...) => return 0xA91F89C4
20619|0x832fdf2: Calling pthread_getspecific (00000003, 08421200, 00000000...) => return 0xA91FCA78
20619|0x80f7114: Calling strlen(0x83fa2c8("SDL could not be initialized: ")) => return 0x0000001E
20619|0x83e6196: Calling fwrite (083FA2C8, 00000001, 0000001E...) =>SDL could not be initialized:  return 0x0000001E
20619|0x83e646e: Calling fflush (B6DBDD90, 00000001, 00000000...) => return 0x00000000
```
Like before i've [uploaded the log](https://ufile.io/689rltwa) just in case.

**Comment by ptitSeb** [comment]
I pushed some improvment again, on x11 dependancies. Hopefully, it will find it's symbols now.

**Comment by ITotalJustice** [comment]
Still the same error, and i believe the same amount of missing symbols. The log looks the same(?) as well. [Uploaded the log again](https://ufile.io/a2yoh5vt) the section with `SDL could not be initialized` looks the same to me as well.

**Comment by ptitSeb** [comment]
Ah, I have noticed in the full log that some symbol were missing from x11 (not visible in regular log, but can be seen with `BOX86_DLSYM_ERROR=1` or with the full `BOX86_LOG=DEBUG` of course).

I have added them, maybe it's better now.

**Comment by ITotalJustice** [comment]
Nice find! that has fixed the `SDL could not be initialized` error. Game still doesn't boot yet. The sdl audio error `SDL_OpenAudioDevice failed: No such audio device` still is displayed. [Full log again](https://ufile.io/yuhh1t4c). [And heres the full missing symbols](https://ufile.io/94tjxq2k) when using `BOX86_DLSYM_ERROR=1`.

**Comment by ptitSeb** [comment]
Ah thanks ! I'll take a look at that tomorrow. I have the feeling there will be more functions this time I'm afraid.

**Comment by ptitSeb** [comment]
I checked the missing symbol. And for alsa, only 1 symbol seems to be missing. I added it. Maybe it will found an audio driver now.

**Comment by ITotalJustice** [comment]
Sadly the audio driver still isn't found :(

**Comment by ptitSeb** [comment]
Can you do a trace `BOX86_DLSYM_ERROR=1` trace again, to check if it goes farther or if it's something else?

**Comment by ITotalJustice** [comment]
I've [uploaded the trace](https://ufile.io/kyth0unp). 

Also i've now tested my whole gog / humble bundle library. Would you like me to still open issues per game or should i wait until these few that are open now are resolved?

**Comment by ptitSeb** [comment]
For al game that are unity based, no need to open.
But for ohter game, yeah, why not.

Thanks for the trace: yeah, it goes farther, but found another unknown symbol: `snd_pcm_get_chmap`
Too bad this part stops at the 1st unknown symbol...

**Comment by ptitSeb** [comment]
And I just pushed the missing function along with a few others.

**Comment by ITotalJustice** [comment]
Here's the new trace after trying with the new build [link](https://ufile.io/ehmilkxq)

**Comment by ptitSeb** [comment]
It seems alsa is now correctly recognized and sound is initialized correctly now.
I assume it still segfault. can you do a gdb backtrace of the crash?

**Comment by ITotalJustice** [comment]
Sure.
```
Thread 1 "box86" received signal SIGSEGV, Segmentation fault.
0xa802756c in Run (emu=0xa80cdb08) at /home/pi/box86/src/emu/x86run.c:629
629	            GD.dword[0] = ED->dword[0];
(gdb) bt
#0  0xa802756c in Run (emu=0xa80cdb08) at /home/pi/box86/src/emu/x86run.c:629
#1  0xa8006cec in main (argc=<optimized out>, argv=<optimized out>, env=<optimized out>) at /home/pi/box86/src/main.c:42
```

**Comment by ptitSeb** [comment]
ah, that's a generic access to some null pointer I'm afraid.
Maybe a last trace with `BOX86_LOG=DEBUG` just in case I see something obviously wrong in the trace.

**Comment by ITotalJustice** [comment]
[Here you go](https://ufile.io/u7avw5iz)

**Comment by ptitSeb** [comment]
Looks like ot doesn't find the Asset folder:
```
Calling fopen("./Assets.dat", "rb") => return 0x00000000
```
Now. I assume the folder is indeed here, but somehow, it "cd" to the folder of "box86" instead of the real Babaisme binary. Maybe try to cp box86 in the same folder (don't use a link, do an actual copy), just to try if it find it's Assets folder like this.

**Comment by ITotalJustice** [comment]
Very good find! I was trying to launch baba inside of its bin32/ folder. Now launching it via `box86 bin32/Chowdren` has the game attempting to boot! I say attempting because it opens a window, then goes fullscreen for 10 seconds, the closes out of fullscreen but the game is still running(?). Cpu usage is still at 100%, though nothing seems to load. No error messages either apart from
```
Loading ./Data/map0.m (Unspecified)
Could not load file ./Data/map0.m
Loading ./Data/levels.m (Unspecified)
Could not load file ./Data/levels.m
Loading ./Data/Languages/lang_en.txt (Unspecified)
Surface: Set scale not implemented: 24 0
SurfaceObject::set_transparent not implemented: 0
Loading /home/pi/.local/share/Baba_Is_You/SettingsC.txt (Unspecified)
Loading /home/pi/.local/share/Baba_Is_You/ba.ba (Unspecified)
Could not load file /home/pi/.local/share/Baba_Is_You/ba.ba
Set window visible: 1
set fullscreen: 1
```
Also, i tried what you said about launching box86 from the game dir. Well in trying that, i forgot to set the LD path, and suprisingly the game did not complain about missing pulse audio and just defaulted back to `libasound` like it usually does, because of this there are no missing symbol errors. Oh and launching ./box86 from the game dir like `./box86 bin32/Chowdren` had the same output as `~/box86/build/box86 bin32/Chowdren` So looks like i need to launch the game outside its bin dir (my bad!).

Anyway as the game still doesnt load correctly, do you want a full log dump or gdb bt?

**Comment by ptitSeb** [comment]
Ah good, it's going farther. And yeah, asla should should work for sound, no need to get the all the pulse-audio missing stuff...
So, there is no crash, but some endless loop. Well, then a `BOX86_LOG=DEBUG` may be usefull. Kill the program when it quit the fullscreen. I suspect there is a loop that will not be usefull at this point, but may make the log huge.

**Comment by ITotalJustice** [comment]
The log was huge, 180MB for the .txt file alone!

[I've trimmed it down a lot and uploaded it](https://ufile.io/1ke31qju) though its still like 60MB. Hopefully thats alright.

**Comment by voltagex** [comment]
"The hosting period for this file has now expired, only premium users can download it."

@ITotalJustice, you can zip a file and attach it directly here, which will be a lot better than a free hosting service.

**Comment by ITotalJustice** [comment]
> "The hosting period for this file has now expired, only premium users can download it."
> 
> @ITotalJustice, you can zip a file and attach it directly here, which will be a lot better than a free hosting service.

Sure, I didn’t actually think of that at the time haha.

I can upload the logs later on today.

**Comment by ptitSeb** [comment]
Baba Is You seems to be running on side.

Can we close this ticket?

**Comment by slock83** [comment]
Works for me too
