### ISSUE TITLE
RMS Express (C#/dotnet46, using mono): Regression with Sep 4, 2022 (76a86e2e) DYNAREC commit

### ISSUE THREAD

**Issue by WheezyE** [ptitSeb/box86#672]
Hey there. I've been taking a break from the Pi & scripting for a while, but I'm back to try to hunt more VARA bugs.

I just wanted to report in on a crash in RMS Express (dotnet46 program running on mono) that I found in 76a86e2e.

I've tried `wine  RMS\ Express.exe` and `BOX86_DYNAREC_BIGBLOCK=0 BOX86_DYNAREC_STRONGMEM=2 wine RMS\ Express.exe`. Turning off dynarec makes the application run, but it runs so slow that it freezes.

System/Software: RPi4B (2GB), RPiOS Bullseye 32-bit (armv7l), wine-7.1, mono, RMS Express 1.7.0.0, VARA 4.6.3 ([install script](https://raw.githubusercontent.com/WheezyE/Winelink/39d2125000b2b0bdd4c93b84eecab42f3add1dc6/install_winelink.sh))

<details><summary>Log1</summary>

```
pi@raspberrypi4:~/.wine/drive_c/RMS Express $ BOX86_LOG=1 wine RMS\ Express.exe 2>&1 | tee rmscrash_box86_76a86e2e.txt
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="RMS Express.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/i386-unix/ntdll.so
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="RMS Express.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/i386-unix/ntdll.so
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for /home/pi/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/lib/wine/i386-unix/libwine.so.1
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using emulated /home/pi/wine/lib/wine/i386-unix/win32u.so
Using native(wrapped) libm.so.6
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /home/pi/wine/lib/wine/i386-unix/winex11.drv.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using emulated /home/pi/wine/lib/wine/i386-unix/ws2_32.so
0024:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.6" not implemented
0024:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.6" not implemented
Using emulated /home/pi/wine/lib/wine/i386-unix/bcrypt.so
Using native(wrapped) libgnutls.so.30
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
Stop waiting for remaining thread 7733
Stop waiting for remaining thread 7734
```
</details>

_Updates on box86 & ham radio: Since Box86 enabled VARA (Windows only) to run on Raspberry Pi, a lot of ham radio people have been doing more with VARA on Linux (see [Pat's forum](https://github.com/la5nta/pat/issues), [KM4ACK's forum](https://groups.io/g/KM4ACK-Pi/search?p=created%2C0%2C%2C1%2C2%2C0%2C0&q=vara), & [N8JJA/xylo04's github](https://github.com/n8jja/Pat-Vara))_

Thank you again!

**Comment by ptitSeb** [comment]
You mean: it's a regression introduced by this commit?

**Comment by WheezyE** [comment]
Yes, that’s right

**Comment by ptitSeb** [comment]
I think that should fix the issue. I would be interresting to see if it's also fix #673 (as I think did some fixes on flags handling).

**Comment by WheezyE** [comment]
Thank you again. With this commit, RMS Express opens, but freezes after I click the Open Session button (to try to test VARA).

<details><summary>Log1 doesn’t show anything useful as far as I can tell</summary>

```

pi@raspberrypi4:~/.wine/drive_c/RMS Express $ BOX86_LOG=1 wine RMS\ Express.exe 2>&1 | tee rmsfreeze.txt
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 45 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="RMS Express.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/i386-unix/ntdll.so
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
BOX86: Wine detected, WINEPRELOADRESERVE=""
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for /home/pi/wine/bin/wine
argv[1]="RMS Express.exe"
Rename process to "wine"
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/bin/../lib/wine/i386-unix/ntdll.so
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for /home/pi/wine/bin/wineserver
Rename process to "wineserver"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /home/pi/wine/lib/wine/i386-unix/libwine.so.1
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using emulated /home/pi/wine/lib/wine/i386-unix/win32u.so
Using native(wrapped) libm.so.6
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0034:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libfontconfig.so.1
Using emulated /home/pi/wine/lib/wine/i386-unix/winex11.drv.so
Using native(wrapped) libXext.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXcursor.so.1
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using emulated /home/pi/wine/lib/wine/i386-unix/ws2_32.so
0024:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.6" not implemented
0024:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.6" not implemented
Using emulated /home/pi/wine/lib/wine/i386-unix/bcrypt.so
Using native(wrapped) libgnutls.so.30
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0021E098, 0025E578, 0021E09C, 0021E090
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0021E098, 0025E578, 0021E09C, 0021E090
0024:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0021E098, 0025E578, 0021E09C, 0021E090
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using emulated /home/pi/wine/lib/wine/i386-unix/dnsapi.so
Using native(wrapped) libresolv.so.2
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0060:fixme:nsi:ipv6_forward_enumerate_all not implemented
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
Using emulated /home/pi/wine/lib/wine/i386-unix/crypt32.so
0024:fixme:uiautomation:UiaClientsAreListening ()
0024:fixme:uiautomation:UiaClientsAreListening ()
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:fixme:uiautomation:UiaClientsAreListening ()
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0050:fixme:imm:ImeSetActiveContext (0x6c6ec0, 0): stub
0050:fixme:imm:ImmReleaseContext (00010020, 006C6EC0): stub
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:fixme:imm:ImeSetActiveContext (0x26efd0, 1): stub
0024:fixme:imm:ImmReleaseContext (0001006E, 0026EFD0): stub
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:fixme:uiautomation:UiaClientsAreListening ()
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.
0024:err:x11settings:X11DRV_EnumDisplaySettingsEx Failed to get L"\\\\.\\DISPLAY1" current display settings.

```
</details>


I also ran BOX86_BIGBLOCK=0 BOX86_STRONGMEM=2, but still get freezing.

**Comment by WheezyE** [comment]
Impressive work. That fixed the crash 🙂
#673 is still present unfortunately. Thank you very much. I’ll close this issue
