### ISSUE TITLE
Steam Big Picture UI no longer works

### ISSUE THREAD

**Issue by theofficialgman** [ptitSeb/box86#740]
After a steam update, the big picture UI no longer works with box86

Loading it produces an UI that looks like this with a mouse:
![Screenshot_2022-12-26_00-36-45](https://user-images.githubusercontent.com/28281419/209483906-355821e6-4671-4f33-a717-fe1b6a8cb1e9.png)

**Comment by ptitSeb** [comment]
I reproduce the issue. I started debugging and it's an issue with the Dynarec. I haven't isolated the root cause yet.

**Comment by ptitSeb** [comment]
I should be fixed now (at least it works fine on my side now). Can you retry with latest box86?

**Comment by theofficialgman** [comment]
Yes that fixes it for me as well.

`-newbigpicture` still does not work for me but I never tested that before

**Comment by ptitSeb** [comment]
`-newbigpicture`? that's a command line argument? Does it launch the SteamDeck UI or something like that?

**Comment by theofficialgman** [comment]
> `-newbigpicture`? that's a command line argument? Does it launch the SteamDeck UI or something like that?

yes and yes

**Comment by ptitSeb** [comment]
Ok, so I quickly tried. This mode seems to require `steamwebhelper` to be actually running. It's currently disabled on box64 because it's still not working yet.
